services:
  - type: web
    name: cardiovision-backend
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: apt-get update -y && apt-get install -y gfortran libopenblas-dev liblapack-dev && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
