services:
  - type: web
    name: cardiovision-backend
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install --upgrade pip && pip install --prefer-binary -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
